app:
  name: "OSS Manager"
  env: "development"  # development, production
  port: 8080
  read_timeout: 60    # 秒
  write_timeout: 60   # 秒
  upload_temp_dir: "./tmp/uploads"
  max_file_size: 1073741824  # 1GB

jwt:
  secret_key: "your-very-secret-key-change-in-production"
  expires_in: 86400  # 24小时（秒）
  issuer: "ossmanager"

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  username: "root"
  password: "admin"
  dbname: "oss_manager"
  sslmode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600  # 1小时（秒）

log:
  level: "debug"  # debug, info, warn, error
  format: "console"  # console, json
  output: "both"  # stdout, file, both
  file_path: "./logs/app.log" 