# MD5计算器配置
app:
  # MD5计算的工作协程数量
  workers: 5  # 默认为5个工作协程，可根据服务器性能调整 

# 阿里云 OSS 配置示例
# 支持传输加速的 bucket 配置
aliyun_oss:
  access_key_id: ""
  access_key_secret: ""
  endpoint: "https://oss-cn-hangzhou.aliyuncs.com"  # 默认endpoint，启用传输加速时会被覆盖
  bucket: "your-bucket-name"
  region: "cn-hangzhou"  # bucket所在区域
  upload_dir: "uploads/"
  url_expire_time: 3600  # URL过期时间（秒）
  
  # 传输加速配置
  transfer_accelerate:
    enabled: true   # 开启传输加速（仅当bucket支持传输加速时才设置为true）
    type: "global"  # 加速类型：
                    # "global" - 全球加速域名: https://oss-accelerate.aliyuncs.com
                    # "overseas" - 海外加速域名: https://oss-accelerate-overseas.aliyuncs.com
  
  # 函数计算配置（用于异步MD5计算）
  function_compute:
    enabled: false  # 是否启用函数计算
    endpoint: "https://1234567890.cn-hangzhou.fc.aliyuncs.com"
    api_version: "2016-08-15"
    access_key_id: "your-fc-access-key-id"
    access_key_secret: "your-fc-access-key-secret"
    service_name: "oss-manager"
    function_name: "calculate-md5"

# AWS S3 配置示例
aws_s3:
  access_key_id: ""
  secret_access_key: ""
  region: "us-east-1"
  bucket: "your-s3-bucket-name"
  upload_dir: "uploads/"
  url_expire_time: 3600

# Cloudflare R2 配置示例
cloudflare_r2:
  account_id: ""
  access_key_id: ""
  secret_access_key: ""
  bucket: "your-r2-bucket-name"
  upload_dir: "uploads/"
  url_expire_time: 3600

# 配置说明：
# 1. 传输加速功能需要在阿里云OSS控制台为对应的bucket开启
# 2. 开启传输加速后，上传和下载速度在全球范围内会有显著提升
# 3. 传输加速会产生额外的费用，请根据实际需求开启
# 4. 如果bucket未开启传输加速，请将transfer_accelerate.enabled设置为false 