aliyun_oss:
  access_key_id: "your-aliyun-access-key-id"
  access_key_secret: "your-aliyun-access-key-secret"
  endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
  bucket: "your-bucket-name"
  region: "cn-hangzhou"
  upload_dir: "uploads/"
  url_expire_time: 14400  # 4 hours in seconds
  transfer_accelerate:
    enabled: false  # 是否开启传输加速（当bucket开启了传输加速功能时设置为true）
    type: "global"  # 加速类型: "global" 全球加速 或 "overseas" 海外加速
    # 注意：启用传输加速后，将使用阿里云的加速域名而不是区域域名
    # global: https://oss-accelerate.aliyuncs.com
    # overseas: https://oss-accelerate-overseas.aliyuncs.com
  function_compute:
    enabled: false  # 默认关闭，避免意外调用
    endpoint: "https://your-account-id.cn-hangzhou.fc.aliyuncs.com"
    api_version: "2016-08-15"
    access_key_id: "your-fc-access-key-id"
    access_key_secret: "your-fc-access-key-secret"
    service_name: "oss-manager"
    function_name: "calculate-md5"

aws_s3:
  access_key_id: "your-aws-access-key-id"
  secret_access_key: "your-aws-secret-access-key"
  region: "us-east-1"
  bucket: "your-s3-bucket-name"
  upload_dir: "uploads/"
  url_expire_time: 3600

cloudflare_r2:
  account_id: "your-account-id"
  access_key_id: "your-r2-access-key-id"
  secret_access_key: "your-r2-secret-access-key"
  bucket: "your-r2-bucket-name"
  upload_dir: "uploads/"
  url_expire_time: 3600
