name: Frontend CI ACR

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4          

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - name: Login to Alibaba Cloud ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}  
          password: ${{ secrets.ACR_PASSWORD }}  

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          build-args: |
            APP_NAME=ossmanager-fronted
            APP_VERSION=${{ steps.get_version.outputs.VERSION }}
          tags: |
            ${{ secrets.ACR_REGISTRY }}/novacloud/ossmanager-fronted:latest
            ${{ secrets.ACR_REGISTRY }}/novacloud/ossmanager-fronted:${{ steps.get_version.outputs.VERSION }}